## application.yml

# Server Port
server:
  port: 8080

# MySQL Info 본인 MySQL로 수정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bch
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# logging
logging:
  level:
    org:
      hibernate:
        # sql
        sql: debug
        type:
          descriptor:
            sql: trace
#    root: debug

#JWT Secret Random code (32바이트 길이의 무작위 바이트 문자열을 64자 길이의 16진수 문자열로 인코딩)
jwt :
  secret : 4626379cadc10451644ebfc33bdef68993cd3edc426640f8c28758cd853dbfa5

  expire :
    #access: 600000 = 2 hour
    access: 6000000
    #refresh: 864000000 = 10 day
    refresh: 864000000

